### ISSUE TITLE
Hackage version is behind github version, fails to compile with ghc-8.8.1

### ISSUE THREAD

**Issue by henrylaxen** [snapframework/snap#215]
The title pretty much says it all.  On hackage, the file RST.hs line 96 is:
`fail msg = RST $ \_ _ -> fail msg`
which causes ghc-8.8.1 to complain with
> src/Snap/Snaplet/Internal/RST.hs:96:5: error:
>     ‘fail’ is not a (visible) method of class ‘Monad’

 while the github version comments out that line:
```
-- instance (Monad m) => MonadFail  (RST r s m) where
 --    fail msg = RST $ \_ _ -> fail msg
```
if you could upload the github version to hackage everything would be tickety-boo
Best wishes,
Henry Laxen
